"""Onboarding: scan a workspace and propose an initial configuration.

Endpoint: POST /v1/onboarding/scan
Response: ScanResult — detected stack, suggested context mode, availability of npx/git.

Rules (INV-6): this module only *proposes* configuration — nothing is applied without
an explicit Apply action from the user (via a separate endpoint or UI action).
"""

from __future__ import annotations

import json
import logging
import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Manifest detection
# ---------------------------------------------------------------------------

_MANIFEST_CANDIDATES: list[tuple[str, str]] = [
    ("package.json", "nodejs"),
    ("pyproject.toml", "python"),
    ("setup.py", "python"),
    ("requirements.txt", "python"),
    ("Cargo.toml", "rust"),
    ("go.mod", "go"),
    ("pom.xml", "java"),
    ("build.gradle", "java"),
    ("Gemfile", "ruby"),
    ("composer.json", "php"),
    (".csproj", "dotnet"),
    ("mix.exs", "elixir"),
]


def _detect_stack(workspace_root: Path) -> list[str]:
    """Return a list of detected technology stack names for the workspace."""
    found: list[str] = []
    for filename, stack in _MANIFEST_CANDIDATES:
        if filename.startswith(".") or "." not in filename:
            # Glob for extension-only patterns like .csproj
            matches = list(workspace_root.glob(f"*{filename}"))
        else:
            matches = list(workspace_root.glob(filename))
        if matches:
            if stack not in found:
                found.append(stack)
    return found


# ---------------------------------------------------------------------------
# Preflight availability checks
# ---------------------------------------------------------------------------

def _check_npx() -> bool:
    return shutil.which("npx") is not None


def _check_git() -> bool:
    return shutil.which("git") is not None


def _context_file_exists(workspace_root: Path) -> bool:
    return (workspace_root / ".swarm" / "context.txt").exists()


# ---------------------------------------------------------------------------
# Suggested config
# ---------------------------------------------------------------------------

def _suggest_context_mode(mcp_available: bool) -> str:
    """Return suggested context mode based on MCP availability.

    Priority follows the hierarchy defined in docs/AIlourOS.md (INV-1):
      1. retrieve_mcp  (if npx is available)
      2. retrieve_fs   (explicit fallback)
    """
    return "retrieve_mcp" if mcp_available else "retrieve_fs"


def _build_proposed_config(
    workspace_root: Path,
    context_mode: str,
    detected_stack: list[str],
) -> str:
    """Generate proposed content for .swarm/context.txt as a preview diff."""
    lines: list[str] = [
        "# .swarm/context.txt — generated by onboarding (review and Apply to save)",
        f"# Detected stack: {', '.join(detected_stack) if detected_stack else 'unknown'}",
        f"# Suggested context mode: {context_mode}",
        "#",
        "# Add glob patterns below (one per line) to include in priority context.",
        "# Lines starting with # are ignored.",
    ]
    if "python" in detected_stack:
        lines += ["src/", "tests/", "*.py"]
    elif "nodejs" in detected_stack:
        lines += ["src/", "tests/", "*.ts", "*.js"]
    elif "rust" in detected_stack:
        lines += ["src/", "tests/"]
    elif "go" in detected_stack:
        lines += ["*.go", "cmd/", "pkg/"]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

@dataclass
class ScanResult:
    workspace_root: str
    detected_stack: list[str] = field(default_factory=list)
    suggested_context_mode: str = "retrieve_fs"
    mcp_available: bool = False
    git_available: bool = False
    context_file_exists: bool = False
    proposed_config_preview: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "workspace_root": self.workspace_root,
            "detected_stack": self.detected_stack,
            "suggested_context_mode": self.suggested_context_mode,
            "mcp_available": self.mcp_available,
            "git_available": self.git_available,
            "context_file_exists": self.context_file_exists,
            "proposed_config_preview": self.proposed_config_preview,
        }


def scan_workspace(workspace_root_str: str) -> ScanResult:
    """Scan *workspace_root_str* and return a ScanResult.

    Does NOT write any files — results are proposals only (INV-6).
    """
    root = Path(workspace_root_str).resolve() if workspace_root_str else Path.cwd()
    if not root.exists():
        logger.warning("onboarding.scan_workspace: workspace_root does not exist: %s", root)
        return ScanResult(workspace_root=str(root))

    mcp_ok = _check_npx()
    git_ok = _check_git()
    stack = _detect_stack(root)
    ctx_exists = _context_file_exists(root)
    mode = _suggest_context_mode(mcp_ok)
    preview = _build_proposed_config(root, mode, stack)

    result = ScanResult(
        workspace_root=str(root),
        detected_stack=stack,
        suggested_context_mode=mode,
        mcp_available=mcp_ok,
        git_available=git_ok,
        context_file_exists=ctx_exists,
        proposed_config_preview=preview,
    )
    logger.info(
        "onboarding.scan_workspace: root=%s stack=%s mcp=%s git=%s ctx_exists=%s mode=%s",
        root, stack, mcp_ok, git_ok, ctx_exists, mode,
    )
    return result


def apply_onboarding_config(workspace_root_str: str, content: str) -> None:
    """Write *content* to .swarm/context.txt — only called after explicit user Apply.

    Raises:
        ValueError: if workspace_root is empty or does not exist.
        PermissionError: if .swarm/ cannot be created.
    """
    if not workspace_root_str or not workspace_root_str.strip():
        raise ValueError("workspace_root must be provided to apply onboarding config")
    root = Path(workspace_root_str).resolve()
    if not root.exists():
        raise ValueError(f"workspace_root does not exist: {root}")

    # Protect against path traversal
    target = (root / ".swarm" / "context.txt").resolve()
    if not str(target).startswith(str(root)):
        raise ValueError("path traversal detected")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    logger.info("onboarding.apply_config: wrote %s (%d chars)", target, len(content))


# ---------------------------------------------------------------------------
# AI Pre-configure (G-4)
# ---------------------------------------------------------------------------

_DEFAULT_BASE_MODEL = os.getenv("SWARM_ONBOARDING_BASE_MODEL", "lm_studio/allenai/olmo-3-32b-think")

_PRECONFIGURE_PROMPT_TEMPLATE = """\
Analyze the project at path: {workspace_root}
Detected technology stack: {stack}

Recommend MCP servers for this project from the following options:
- filesystem: for on-demand file reading (always recommend)
- git: for git operations like diff, log, blame (always recommend)
- everything: broad capability set (recommend for Node.js projects)
- memory: persistent agent memory (recommend if project has complex state)

Also suggest the best context_mode from: retrieve_mcp, retrieve_fs, priority_paths, index_only, full
And list up to 5 priority_paths (relative paths that agents should focus on first).

Return ONLY valid JSON with this exact structure:
{{
  "mcp_servers": ["filesystem", "git"],
  "context_mode": "retrieve_mcp",
  "priority_paths": ["src/", "tests/"]
}}
"""


@dataclass
class PreconfigureResult:
    """Result of AI pre-configure — proposals only, nothing is applied (INV-6)."""

    mcp_recommendations: list[str] = field(default_factory=list)
    context_mode: str = "retrieve_mcp"
    priority_paths: list[str] = field(default_factory=list)
    raw_response: str = ""
    error: str = ""
    base_model: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "mcp_recommendations": self.mcp_recommendations,
            "context_mode": self.context_mode,
            "priority_paths": self.priority_paths,
            "raw_response": self.raw_response,
            "error": self.error,
            "base_model": self.base_model,
        }


def _parse_preconfigure_response(raw: str) -> dict[str, Any]:
    """Extract JSON from LLM response — handles markdown code fences."""
    text = raw.strip()
    # Strip markdown code fences if present
    if "```" in text:
        lines = text.split("\n")
        inside = False
        json_lines: list[str] = []
        for line in lines:
            if line.strip().startswith("```"):
                inside = not inside
                continue
            if inside:
                json_lines.append(line)
        text = "\n".join(json_lines).strip()
    # Try to find first { ... } block
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]
    return json.loads(text)


def run_ai_preconfigure(workspace_root: str, base_model: str = "") -> PreconfigureResult:
    """Call the base LLM to analyze the project and recommend MCP servers.

    Returns PreconfigureResult with recommendations only — does NOT write any files (INV-6).
    Explicit Apply by the user is required to persist anything.

    Falls back gracefully if LLM is unavailable — logs the fallback explicitly (INV-1).
    """
    root = Path(workspace_root).resolve() if workspace_root else Path.cwd()
    model = base_model or os.getenv("SWARM_ONBOARDING_BASE_MODEL", _DEFAULT_BASE_MODEL)
    stack = _detect_stack(root)

    prompt = _PRECONFIGURE_PROMPT_TEMPLATE.format(
        workspace_root=str(root),
        stack=", ".join(stack) if stack else "unknown",
    )

    raw_response = ""
    try:
        from backend.App.integrations.infrastructure.llm.client import chat_completion_text

        raw_response = chat_completion_text(
            model=model,
            messages=[{"role": "user", "content": prompt}],
        )
        parsed = _parse_preconfigure_response(raw_response)
        mcp_recs = parsed.get("mcp_servers", ["filesystem", "git"])
        if not isinstance(mcp_recs, list):
            mcp_recs = ["filesystem", "git"]
        ctx_mode = str(parsed.get("context_mode", "retrieve_mcp"))
        priority = parsed.get("priority_paths", [])
        if not isinstance(priority, list):
            priority = []

        logger.info(
            "onboarding.run_ai_preconfigure: model=%s mcp=%s ctx=%s",
            model,
            mcp_recs,
            ctx_mode,
        )
        return PreconfigureResult(
            mcp_recommendations=mcp_recs,
            context_mode=ctx_mode,
            priority_paths=priority,
            raw_response=raw_response,
            base_model=model,
        )

    except Exception as exc:
        # INV-1: explicit fallback logging — never silent
        logger.warning(
            "onboarding.run_ai_preconfigure: LLM call failed (model=%s), "
            "falling back to defaults. error=%s",
            model,
            exc,
        )
        mcp_available = _check_npx()
        return PreconfigureResult(
            mcp_recommendations=["filesystem", "git"],
            context_mode=_suggest_context_mode(mcp_available),
            priority_paths=[],
            raw_response=raw_response,
            error=str(exc),
            base_model=model,
        )
