from __future__ import annotations

import json
import logging
import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_MANIFEST_CANDIDATES: list[tuple[str, str]] = [
    ("package.json", "nodejs"),
    ("pyproject.toml", "python"),
    ("setup.py", "python"),
    ("requirements.txt", "python"),
    ("Cargo.toml", "rust"),
    ("go.mod", "go"),
    ("pom.xml", "java"),
    ("build.gradle", "java"),
    ("Gemfile", "ruby"),
    ("composer.json", "php"),
    (".csproj", "dotnet"),
    ("mix.exs", "elixir"),
]


def _detect_stack(workspace_root: Path) -> list[str]:
    found: list[str] = []
    for filename, stack in _MANIFEST_CANDIDATES:
        if filename.startswith(".") or "." not in filename:
            matches = list(workspace_root.glob(f"*{filename}"))
        else:
            matches = list(workspace_root.glob(filename))
        if matches:
            if stack not in found:
                found.append(stack)
    return found


def _check_npx() -> bool:
    return shutil.which("npx") is not None


def _check_git() -> bool:
    return shutil.which("git") is not None


def _context_file_exists(workspace_root: Path) -> bool:
    return (workspace_root / ".swarm" / "context.txt").exists()


def _workspace_has_git_repo(workspace_root: Path) -> bool:
    return (workspace_root / ".git").exists()


def _suggest_context_mode(mcp_available: bool) -> str:
    return "retrieve_mcp" if mcp_available else "retrieve_fs"


def _default_mcp_recommendations(workspace_root: Path) -> list[str]:
    recommendations = ["filesystem"]
    if _workspace_has_git_repo(workspace_root):
        recommendations.append("git")
    return recommendations


def _sanitize_mcp_recommendations(
    recommendations: Any,
    workspace_root: Path,
) -> list[str]:
    defaults = _default_mcp_recommendations(workspace_root)
    if not isinstance(recommendations, list):
        return defaults

    sanitized: list[str] = []
    workspace_has_git = _workspace_has_git_repo(workspace_root)
    for item in recommendations:
        name = str(item or "").strip()
        if not name:
            continue
        if name == "git" and not workspace_has_git:
            continue
        if name not in sanitized:
            sanitized.append(name)

    if "filesystem" not in sanitized:
        sanitized.insert(0, "filesystem")
    return sanitized


def _build_proposed_config(
    workspace_root: Path,
    context_mode: str,
    detected_stack: list[str],
) -> str:
    lines: list[str] = [
        "# .swarm/context.txt — generated by onboarding (review and Apply to save)",
        f"# Detected stack: {', '.join(detected_stack) if detected_stack else 'unknown'}",
        f"# Suggested context mode: {context_mode}",
        "#",
        "# Add glob patterns below (one per line) to include in priority context.",
        "# Lines starting with # are ignored.",
    ]
    if "python" in detected_stack:
        lines += ["src/", "tests/", "*.py"]
    elif "nodejs" in detected_stack:
        lines += ["src/", "tests/", "*.ts", "*.js"]
    elif "rust" in detected_stack:
        lines += ["src/", "tests/"]
    elif "go" in detected_stack:
        lines += ["*.go", "cmd/", "pkg/"]
    return "\n".join(lines)


@dataclass
class ScanResult:
    workspace_root: str
    detected_stack: list[str] = field(default_factory=list)
    suggested_context_mode: str = "retrieve_fs"
    mcp_available: bool = False
    git_available: bool = False
    workspace_has_git_repo: bool = False
    context_file_exists: bool = False
    proposed_config_preview: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "workspace_root": self.workspace_root,
            "detected_stack": self.detected_stack,
            "suggested_context_mode": self.suggested_context_mode,
            "mcp_available": self.mcp_available,
            "git_available": self.git_available,
            "workspace_has_git_repo": self.workspace_has_git_repo,
            "context_file_exists": self.context_file_exists,
            "proposed_config_preview": self.proposed_config_preview,
        }


def scan_workspace(workspace_root_str: str) -> ScanResult:
    root = Path(workspace_root_str).resolve() if workspace_root_str else Path.cwd()
    if not root.exists():
        logger.warning("onboarding.scan_workspace: workspace_root does not exist: %s", root)
        return ScanResult(workspace_root=str(root))

    mcp_ok = _check_npx()
    git_ok = _check_git()
    workspace_has_git = _workspace_has_git_repo(root)
    stack = _detect_stack(root)
    ctx_exists = _context_file_exists(root)
    mode = _suggest_context_mode(mcp_ok)
    preview = _build_proposed_config(root, mode, stack)

    result = ScanResult(
        workspace_root=str(root),
        detected_stack=stack,
        suggested_context_mode=mode,
        mcp_available=mcp_ok,
        git_available=git_ok,
        workspace_has_git_repo=workspace_has_git,
        context_file_exists=ctx_exists,
        proposed_config_preview=preview,
    )
    logger.info(
        "onboarding.scan_workspace: root=%s stack=%s mcp=%s git=%s ctx_exists=%s mode=%s",
        root, stack, mcp_ok, git_ok, ctx_exists, mode,
    )
    return result


def apply_onboarding_config(workspace_root_str: str, content: str) -> None:
    if not workspace_root_str or not workspace_root_str.strip():
        raise ValueError("workspace_root must be provided to apply onboarding config")
    root = Path(workspace_root_str).resolve()
    if not root.exists():
        raise ValueError(f"workspace_root does not exist: {root}")

    target = (root / ".swarm" / "context.txt").resolve()
    if not str(target).startswith(str(root)):
        raise ValueError("path traversal detected")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    logger.info("onboarding.apply_config: wrote %s (%d chars)", target, len(content))


def _resolve_default_base_model() -> str:
    explicit = os.getenv("SWARM_ONBOARDING_BASE_MODEL", "").strip()
    if explicit:
        return explicit
    if os.getenv("AILOUROS_DESKTOP", "").strip() == "1":
        return "openai/local-default"
    return "lm_studio/allenai/olmo-3-32b-think"


_DEFAULT_BASE_MODEL = _resolve_default_base_model()

_PRECONFIGURE_PROMPT_TEMPLATE = """\
Analyze the project at path: {workspace_root}
Detected technology stack: {stack}
Workspace is a Git repository: {workspace_has_git_repo}

Recommend MCP servers for this project from the following options:
- filesystem: for on-demand file reading (always recommend)
- git: for git operations like diff, log, blame (recommend only if workspace is a Git repository)
- everything: broad capability set (recommend for Node.js projects)
- memory: persistent agent memory (recommend if project has complex state)

Also suggest the best context_mode from: retrieve_mcp, retrieve_fs, priority_paths, index_only, full
And list up to 5 priority_paths (relative paths that agents should focus on first).

Return ONLY valid JSON with this exact structure:
{{
  "mcp_servers": ["filesystem", "git"],
  "context_mode": "retrieve_mcp",
  "priority_paths": ["src/", "tests/"]
}}
"""


@dataclass
class PreconfigureResult:
    mcp_recommendations: list[str] = field(default_factory=list)
    context_mode: str = "retrieve_mcp"
    priority_paths: list[str] = field(default_factory=list)
    raw_response: str = ""
    error: str = ""
    base_model: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "mcp_recommendations": self.mcp_recommendations,
            "context_mode": self.context_mode,
            "priority_paths": self.priority_paths,
            "raw_response": self.raw_response,
            "error": self.error,
            "base_model": self.base_model,
        }


def _parse_preconfigure_response(raw: str) -> dict[str, Any]:
    text = raw.strip()
    if "```" in text:
        lines = text.split("\n")
        inside = False
        json_lines: list[str] = []
        for line in lines:
            if line.strip().startswith("```"):
                inside = not inside
                continue
            if inside:
                json_lines.append(line)
        text = "\n".join(json_lines).strip()
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]
    return json.loads(text)


def get_mcp_config_payload(workspace_root: str) -> dict[str, Any]:
    from backend.App.integrations.infrastructure.mcp.auto.setup import load_mcp_config

    config = load_mcp_config(workspace_root) or {"version": "1", "servers": []}
    return {"workspace_root": workspace_root, "config": config}


def apply_mcp_config_payload(
    workspace_root: str,
    config: dict[str, Any] | None,
    servers: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    from backend.App.integrations.infrastructure.mcp.auto.setup import save_mcp_config

    if not workspace_root or not workspace_root.strip():
        raise ValueError("workspace_root must not be empty")

    if config is not None:
        effective_config = config
    elif servers is not None:
        effective_config = {"version": "1", "servers": servers}
    else:
        raise ValueError("Either config or servers must be provided")

    path = save_mcp_config(workspace_root, effective_config)
    return {"status": "ok", "path": str(path)}


def mcp_preflight_payload(
    workspace_root: str,
    *,
    tavily_api_key: str | None = None,
    exa_api_key: str | None = None,
    scrapingdog_api_key: str | None = None,
) -> dict[str, Any]:
    from backend.App.integrations.infrastructure.mcp.auto.setup import load_mcp_config
    from backend.App.integrations.infrastructure.mcp.stdio.mcp_pool import mcp_preflight_check

    config = load_mcp_config(workspace_root) or {}
    servers = config.get("servers", [])
    results: list[dict[str, Any]] = []
    for server in servers:
        result = mcp_preflight_check(server)
        results.append(result)
    return {"servers": results}


def preconfigure_payload(workspace_root: str, base_model: str = "") -> dict[str, Any]:
    result = run_ai_preconfigure(workspace_root, base_model)
    return result.to_dict()


def onboarding_models_payload(workspace_root: str = "") -> dict[str, Any]:
    from backend.App.integrations.infrastructure.model_discovery import (
        discover_lm_studio_models,
        discover_ollama_models,
    )

    ollama = [m.model_id for m in discover_ollama_models()]
    lmstudio = [m.model_id for m in discover_lm_studio_models()]
    assignments = _build_role_assignments(ollama, lmstudio)
    return {
        "ollama": ollama,
        "lm_studio": lmstudio,
        "assignments": assignments,
    }


_DESKTOP_ROLES: tuple[str, ...] = (
    "pm",
    "ba",
    "architect",
    "code_quality_architect",
    "reviewer",
    "stack_reviewer",
    "ux_researcher",
    "ux_architect",
    "ui_designer",
    "image_generator",
    "audio_generator",
    "dev",
    "qa",
    "problem_spotter",
    "refactor_plan",
    "code_diagram",
    "doc_generate",
    "devops",
    "dev_lead",
    "seo_specialist",
    "ai_citation_strategist",
    "app_store_optimizer",
)


def _build_role_assignments(
    ollama: list[str],
    lmstudio: list[str],
) -> list[dict[str, str]]:
    if os.getenv("AILOUROS_DESKTOP", "").strip() == "1":
        local_id = _first_local_model_id() or "local-default"
        return [
            {
                "role": role,
                "model_id": local_id,
                "provider": "local",
                "reason": "Bundled local model",
            }
            for role in _DESKTOP_ROLES
        ]

    if ollama:
        chosen, provider = ollama[0], "ollama"
    elif lmstudio:
        chosen, provider = lmstudio[0], "lm_studio"
    else:
        return []
    return [
        {
            "role": role,
            "model_id": chosen,
            "provider": provider,
            "reason": "First discovered local provider",
        }
        for role in _DESKTOP_ROLES
    ]


def _first_local_model_id() -> str:
    raw_dir = os.getenv("AILOUROS_MODELS_DIR", "").strip()
    if not raw_dir:
        return ""
    models_dir = Path(raw_dir).expanduser()
    if not models_dir.is_dir():
        return ""
    for entry in sorted(models_dir.glob("*.gguf")):
        return entry.stem
    return ""


def run_ai_preconfigure(workspace_root: str, base_model: str = "") -> PreconfigureResult:
    root = Path(workspace_root).resolve() if workspace_root else Path.cwd()
    model = base_model or os.getenv("SWARM_ONBOARDING_BASE_MODEL", _DEFAULT_BASE_MODEL)
    stack = _detect_stack(root)
    workspace_has_git_repo = _workspace_has_git_repo(root)

    prompt = _PRECONFIGURE_PROMPT_TEMPLATE.format(
        workspace_root=str(root),
        stack=", ".join(stack) if stack else "unknown",
        workspace_has_git_repo="yes" if workspace_has_git_repo else "no",
    )

    raw_response = ""
    try:
        from backend.App.integrations.infrastructure.llm.client import chat_completion_text

        raw_response = chat_completion_text(
            model=model,
            messages=[{"role": "user", "content": prompt}],
        )
        parsed = _parse_preconfigure_response(raw_response)
        mcp_recs = _sanitize_mcp_recommendations(parsed.get("mcp_servers"), root)
        ctx_mode = str(parsed.get("context_mode", "retrieve_mcp"))
        priority = parsed.get("priority_paths", [])
        if not isinstance(priority, list):
            priority = []

        logger.info(
            "onboarding.run_ai_preconfigure: model=%s mcp=%s ctx=%s",
            model,
            mcp_recs,
            ctx_mode,
        )
        return PreconfigureResult(
            mcp_recommendations=mcp_recs,
            context_mode=ctx_mode,
            priority_paths=priority,
            raw_response=raw_response,
            base_model=model,
        )

    except Exception as exc:
        logger.warning(
            "onboarding.run_ai_preconfigure: LLM call failed (model=%s), "
            "falling back to defaults. error=%s",
            model,
            exc,
        )
        mcp_available = _check_npx()
        return PreconfigureResult(
            mcp_recommendations=_default_mcp_recommendations(root),
            context_mode=_suggest_context_mode(mcp_available),
            priority_paths=[],
            raw_response=raw_response,
            error=str(exc),
            base_model=model,
        )
