from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

from backend.App.spec.application.context_assembler import (
    CodegenContextAssembler,
    context_disabled,
)
from backend.App.spec.application.diagnostic_prompt import RetryDiagnostic, format_diagnostic
from backend.App.spec.domain.codegen_mode import CodegenMode, choose_mode
from backend.App.spec.domain.file_diff import DiffApplyError, DiffParseError, apply_diff, parse_unified_diff
from backend.App.spec.domain.keep_regions import apply_keep_regions
from backend.App.spec.domain.ports import (
    CodeVerifier,
    LLMClient,
    RepoMapPort,
    SpecGraphPort,
    VerificationFinding,
)
from backend.App.spec.domain.provenance import ProvenanceSidecar
from backend.App.spec.domain.spec_document import SpecDocument
from backend.App.spec.infrastructure.repomap_adapter import TreeSitterRepoMapAdapter
from backend.App.spec.infrastructure.sidecar_store import write_sidecar
from backend.App.spec.infrastructure.spec_graph_adapter import FilesystemSpecGraphAdapter
from backend.App.spec.infrastructure.spec_repository_fs import FilesystemSpecRepository

_ENV_STUB = "SWARM_SPEC_CODEGEN_STUB"
_ENV_MAX_RETRIES = "SWARM_SPEC_CODEGEN_MAX_RETRIES"
_ENV_DIFF_MAX_RETRIES = "SWARM_SPEC_CODEGEN_DIFF_MAX_RETRIES"
_DEFAULT_MODEL = "stub"
_DEFAULT_SEED = 0
_MAX_RETRY = 3
_DIFF_MAX_RETRY = 2

_log = logging.getLogger(__name__)


class CodegenError(Exception):
    pass


class NoLLMClientConfigured(CodegenError):
    pass


@dataclass(frozen=True)
class CodegenRequest:
    spec_id: str
    model_name: str = _DEFAULT_MODEL
    seed: int = _DEFAULT_SEED
    codegen_mode: Optional[CodegenMode] = None
    use_n_best: bool = False
    n_best_n: int = 3
    n_best_strategy: str = "lowest_error"
    n_best_temperature: float = 0.7


@dataclass(frozen=True)
class AttemptRecord:
    attempt: int
    finding_count: int
    first_findings: tuple[VerificationFinding, ...]
    mode: CodegenMode = "full_file"
    diff_apply_error: Optional[str] = None


@dataclass(frozen=True)
class CodegenOutcome:
    spec_id: str
    written_files: tuple[str, ...]
    sidecar_paths: tuple[str, ...]
    retry_count: int
    verification_attempts: tuple[AttemptRecord, ...] = field(default_factory=tuple)


def _build_prompt(spec_id: str, contract: str, behaviour: str, examples: str) -> str:
    return (
        f"# Codegen target: {spec_id}\n\n"
        f"## Public Contract\n{contract}\n\n"
        f"## Behaviour\n{behaviour}\n\n"
        f"## Examples\n{examples}\n"
    )


def _build_diff_prompt(
    target_path: str,
    existing_content: str,
    spec_prompt: str,
) -> str:
    return (
        f"Return a unified diff against the EXISTING file content shown below. "
        f"Do not return a whole file. Use @@ hunk markers only.\n\n"
        f"## Target path\n\n{target_path}\n\n"
        f"## Current file content\n\n{existing_content}\n\n"
        f"## Spec\n\n{spec_prompt}"
    )


def _utc_now_iso() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _stub_generate(prompt: str, *, model: str, seed: int) -> str:
    return f"# generated by stub\n# model={model} seed={seed}\n# prompt_len={len(prompt)}\n"


class _StubLLMClient:
    def generate(self, prompt: str, *, model: str, seed: int) -> str:
        return _stub_generate(prompt, model=model, seed=seed)


def _resolve_llm_client(client: Optional[LLMClient]) -> LLMClient:
    if client is not None:
        return client
    if os.environ.get(_ENV_STUB, "").strip() == "1":
        return _StubLLMClient()
    raise NoLLMClientConfigured(
        f"No LLM client provided and {_ENV_STUB} is not set to '1'. "
        "Pass an LLMClient or set SWARM_SPEC_CODEGEN_STUB=1 for testing."
    )


def _max_retries() -> int:
    raw = os.environ.get(_ENV_MAX_RETRIES, "").strip()
    if raw.isdigit():
        return int(raw)
    return _MAX_RETRY


def _diff_max_retries() -> int:
    raw = os.environ.get(_ENV_DIFF_MAX_RETRIES, "").strip()
    if raw.isdigit():
        return int(raw)
    return _DIFF_MAX_RETRY


def _write_targets(
    document: SpecDocument,
    ws_path: Path,
    generated_text: str,
    request: CodegenRequest,
    spec_hash: str,
    spec_version: int,
    retry_count: int,
) -> tuple[list[str], list[str]]:
    written_files: list[str] = []
    sidecar_paths: list[str] = []
    generated_at = _utc_now_iso()

    for target_rel in document.frontmatter.codegen_targets:
        target_path = ws_path / target_rel
        try:
            target_path.relative_to(ws_path)
        except ValueError as exc:
            raise CodegenError(
                f"codegen_target {target_rel!r} resolves outside workspace"
            ) from exc

        final_text = generated_text
        if target_path.is_file():
            try:
                existing = target_path.read_text(encoding="utf-8")
                final_text = apply_keep_regions(existing, generated_text)
            except OSError as exc:
                raise CodegenError(
                    f"failed to read existing file {target_path}: {exc}"
                ) from exc

        target_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            target_path.write_text(final_text, encoding="utf-8")
        except OSError as exc:
            raise CodegenError(
                f"failed to write {target_path}: {exc}"
            ) from exc
        written_files.append(target_rel)

        sidecar = ProvenanceSidecar(
            spec_id=request.spec_id,
            spec_version=spec_version,
            spec_hash=spec_hash,
            generated_at=generated_at,
            model=request.model_name,
            seed=request.seed,
            retry_count=retry_count,
            keep_regions=(),
        )
        try:
            sidecar_path = write_sidecar(sidecar, target_path, ws_path)
        except Exception as exc:
            raise CodegenError(
                f"failed to write sidecar for {target_path}: {exc}"
            ) from exc
        sidecar_paths.append(str(sidecar_path.relative_to(ws_path)))

    return written_files, sidecar_paths


def _write_targets_diff(
    document: SpecDocument,
    ws_path: Path,
    diff_text: str,
    request: CodegenRequest,
    spec_hash: str,
    spec_version: int,
    retry_count: int,
) -> tuple[list[str], list[str]]:
    written_files: list[str] = []
    sidecar_paths: list[str] = []
    generated_at = _utc_now_iso()

    parsed = parse_unified_diff(diff_text)
    if not parsed.hunks:
        raise DiffParseError(0, "LLM response contained no hunk markers; expected a unified diff")

    for target_rel in document.frontmatter.codegen_targets:
        target_path = ws_path / target_rel
        try:
            target_path.relative_to(ws_path)
        except ValueError as exc:
            raise CodegenError(
                f"codegen_target {target_rel!r} resolves outside workspace"
            ) from exc

        try:
            existing_content = target_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise CodegenError(
                f"diff mode requires existing file but failed to read {target_path}: {exc}"
            ) from exc

        patched = apply_diff(existing_content, parsed)
        final_text = apply_keep_regions(existing_content, patched)

        target_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            target_path.write_text(final_text, encoding="utf-8")
        except OSError as exc:
            raise CodegenError(
                f"failed to write {target_path}: {exc}"
            ) from exc
        written_files.append(target_rel)

        sidecar = ProvenanceSidecar(
            spec_id=request.spec_id,
            spec_version=spec_version,
            spec_hash=spec_hash,
            generated_at=generated_at,
            model=request.model_name,
            seed=request.seed,
            retry_count=retry_count,
            keep_regions=(),
        )
        try:
            sidecar_path = write_sidecar(sidecar, target_path, ws_path)
        except Exception as exc:
            raise CodegenError(
                f"failed to write sidecar for {target_path}: {exc}"
            ) from exc
        sidecar_paths.append(str(sidecar_path.relative_to(ws_path)))

    return written_files, sidecar_paths


def _collect_error_findings(
    verifiers: tuple[CodeVerifier, ...],
    ws_path: Path,
    written: tuple[str, ...],
) -> tuple[VerificationFinding, ...]:
    all_findings: list[VerificationFinding] = []
    for verifier in verifiers:
        all_findings.extend(verifier.verify(ws_path, written))
    return tuple(f for f in all_findings if f.severity == "error")


def noop_recorder(
    spec_id: str,
    agent: str,
    retry_history: list[AttemptRecord],
    final_exception: Optional[Exception] = None,
) -> None:
    pass


def noop_retriever(spec_id: str) -> str:
    return ""


def _build_context_block(
    workspace_root: str | Path,
    document: SpecDocument,
    repo_map_port: Optional[RepoMapPort],
    spec_graph_port: Optional[SpecGraphPort],
) -> str:
    if context_disabled():
        return ""
    repo_map = repo_map_port if repo_map_port is not None else TreeSitterRepoMapAdapter()
    spec_graph = spec_graph_port if spec_graph_port is not None else FilesystemSpecGraphAdapter()
    assembler = CodegenContextAssembler(repo_map=repo_map, spec_graph=spec_graph)
    return assembler.assemble(workspace_root, document)


def _attempt_diff_generation(
    client: LLMClient,
    request: CodegenRequest,
    document: SpecDocument,
    ws_path: Path,
    base_prompt: str,
    spec_hash: str,
    spec_version: int,
    llm_retry_count: int,
) -> tuple[list[str], list[str], Optional[str]]:
    diff_max = _diff_max_retries()
    last_error: Optional[str] = None

    first_target_rel = document.frontmatter.codegen_targets[0]
    first_target_path = ws_path / first_target_rel
    try:
        existing_content = first_target_path.read_text(encoding="utf-8")
    except OSError as exc:
        return [], [], f"cannot read existing file for diff: {exc}"

    diff_prompt = _build_diff_prompt(first_target_rel, existing_content, base_prompt)

    for diff_attempt in range(diff_max):
        try:
            diff_text = client.generate(
                diff_prompt,
                model=request.model_name,
                seed=request.seed,
            )
        except Exception as exc:
            last_error = f"LLM error on diff attempt {diff_attempt + 1}: {exc}"
            continue

        try:
            written_files, sidecar_paths = _write_targets_diff(
                document, ws_path, diff_text, request, spec_hash, spec_version,
                llm_retry_count + diff_attempt,
            )
            return written_files, sidecar_paths, None
        except (DiffParseError, DiffApplyError, CodegenError) as exc:
            last_error = str(exc)
            _log.info(
                "diff attempt %d/%d failed for spec %r: %s",
                diff_attempt + 1,
                diff_max,
                request.spec_id,
                last_error,
            )

    return [], [], last_error


def noop_feedback_retriever(spec_id: str, target_file: str) -> str:
    return ""


def run_codegen(
    workspace_root: str | Path,
    request: CodegenRequest,
    *,
    llm_client: Optional[LLMClient] = None,
    verifiers: tuple[CodeVerifier, ...] = (),
    postmortem_recorder: Optional[Callable] = None,
    postmortem_retriever: Optional[Callable] = None,
    feedback_retriever: Optional[Callable] = None,
    repo_map_port: Optional[RepoMapPort] = None,
    spec_graph_port: Optional[SpecGraphPort] = None,
) -> CodegenOutcome:
    recorder = postmortem_recorder if postmortem_recorder is not None else noop_recorder
    retriever = postmortem_retriever if postmortem_retriever is not None else noop_retriever
    fb_retriever = feedback_retriever if feedback_retriever is not None else noop_feedback_retriever

    client = _resolve_llm_client(llm_client)
    repository = FilesystemSpecRepository(workspace_root)
    ws_path = repository._workspace_root

    document = repository.load(request.spec_id)
    if not document.frontmatter.codegen_targets:
        raise CodegenError(
            f"spec {request.spec_id!r} has no codegen_targets defined"
        )

    _use_n_best = request.use_n_best or document.frontmatter.complexity == "high"
    if _use_n_best:
        import backend.App.spec.application.n_best_codegen as _nbm
        return _nbm.run_n_best_codegen(
            workspace_root,
            request,
            llm_client=client,
            verifiers=verifiers,
            n=request.n_best_n,
            strategy=request.n_best_strategy,
            temperature=request.n_best_temperature,
        )

    contract = document.section("Public Contract")
    behaviour = document.section("Behaviour")
    examples = document.section("Examples")
    spec_hash = document.codegen_hash()
    spec_version = document.frontmatter.version

    context_block = _build_context_block(
        workspace_root, document, repo_map_port, spec_graph_port
    )

    base_prompt = _build_prompt(request.spec_id, contract, behaviour, examples)
    if context_block:
        base_prompt = context_block + "\n" + base_prompt

    first_target_for_feedback = (
        document.frontmatter.codegen_targets[0]
        if document.frontmatter.codegen_targets
        else ""
    )
    feedback_block = fb_retriever(request.spec_id, first_target_for_feedback)
    if feedback_block:
        base_prompt = feedback_block + "\n\n" + base_prompt

    past_failures_block = retriever(request.spec_id)
    if past_failures_block:
        base_prompt = past_failures_block + "\n\n" + base_prompt

    first_target_rel = document.frontmatter.codegen_targets[0]
    first_target_path = ws_path / first_target_rel
    spec_status = document.frontmatter.status

    force_full = request.codegen_mode == "full_file"
    force_diff = request.codegen_mode == "diff"
    effective_mode = choose_mode(
        target_path_exists=first_target_path.is_file(),
        spec_status=spec_status,
        force_full=force_full,
        force_diff=force_diff,
    )

    llm_retry_count = 0
    max_retries = _max_retries()
    attempt_records: list[AttemptRecord] = []
    active_mode = effective_mode
    written_files: list[str] = []
    sidecar_paths: list[str] = []
    generated_text = ""

    if active_mode == "diff":
        written_files, sidecar_paths, diff_error = _attempt_diff_generation(
            client, request, document, ws_path, base_prompt,
            spec_hash, spec_version, llm_retry_count,
        )
        if diff_error is not None:
            _log.info(
                "diff-mode exhausted for spec %r; escalating to full_file. reason: %s",
                request.spec_id,
                diff_error,
            )
            attempt_records.append(
                AttemptRecord(
                    attempt=0,
                    finding_count=0,
                    first_findings=(),
                    mode="diff",
                    diff_apply_error=diff_error,
                )
            )
            active_mode = "full_file"

    if active_mode == "full_file":
        current_prompt = base_prompt
        for attempt in range(max_retries):
            try:
                generated_text = client.generate(
                    current_prompt,
                    model=request.model_name,
                    seed=request.seed,
                )
                break
            except Exception as exc:
                llm_retry_count = attempt + 1
                if attempt + 1 >= max_retries:
                    raise CodegenError(
                        f"LLM generation failed after {max_retries} attempts: {exc}"
                    ) from exc

        written_files, sidecar_paths = _write_targets(
            document, ws_path, generated_text, request, spec_hash, spec_version, llm_retry_count
        )

    if not verifiers:
        return CodegenOutcome(
            spec_id=request.spec_id,
            written_files=tuple(written_files),
            sidecar_paths=tuple(sidecar_paths),
            retry_count=llm_retry_count,
            verification_attempts=tuple(attempt_records),
        )

    written_tuple = tuple(written_files)
    verify_attempt = 1

    while True:
        error_findings = _collect_error_findings(verifiers, ws_path, written_tuple)
        if not error_findings:
            break

        record = AttemptRecord(
            attempt=verify_attempt,
            finding_count=len(error_findings),
            first_findings=error_findings[:3],
            mode=active_mode,
        )
        attempt_records.append(record)

        if verify_attempt >= max_retries:
            recorder(request.spec_id, request.model_name, attempt_records)
            raise CodegenError(
                f"Code verification failed after {max_retries} attempt(s). "
                f"Retry history: "
                + "; ".join(
                    f"attempt {r.attempt}: {r.finding_count} error(s) "
                    f"(e.g. {r.first_findings[0].message!r})"
                    for r in attempt_records
                    if r.finding_count > 0
                )
            )

        diagnostic = RetryDiagnostic(
            attempt=verify_attempt,
            previous_code=generated_text,
            findings=error_findings,
        )
        current_prompt = format_diagnostic(diagnostic) + "\n\n" + base_prompt

        try:
            generated_text = client.generate(
                current_prompt,
                model=request.model_name,
                seed=request.seed,
            )
        except Exception as exc:
            raise CodegenError(
                f"LLM generation failed on verification retry {verify_attempt}: {exc}"
            ) from exc

        written_files, sidecar_paths = _write_targets(
            document,
            ws_path,
            generated_text,
            request,
            spec_hash,
            spec_version,
            llm_retry_count + verify_attempt,
        )
        written_tuple = tuple(written_files)
        verify_attempt += 1

    return CodegenOutcome(
        spec_id=request.spec_id,
        written_files=tuple(written_files),
        sidecar_paths=tuple(sidecar_paths),
        retry_count=llm_retry_count + (verify_attempt - 1),
        verification_attempts=tuple(attempt_records),
    )


__all__ = [
    "AttemptRecord",
    "CodegenError",
    "CodegenOutcome",
    "CodegenRequest",
    "NoLLMClientConfigured",
    "noop_feedback_retriever",
    "noop_recorder",
    "noop_retriever",
    "run_codegen",
    "_build_prompt",
    "_collect_error_findings",
    "_utc_now_iso",
    "_write_targets",
]
